# Generated by Django 3.1.7 on 2021-03-25 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pledges', '0002_auto_20210325_2146'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SelectResponse',
            new_name='Select',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='free_resp',
            new_name='response_number',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='select_resp',
            new_name='response_select',
        ),
    ]
