# Generated by Django 3.1.7 on 2021-03-25 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pledges', '0004_auto_20210325_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='version',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
