# Generated by Django 3.1.7 on 2021-03-25 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pledges', '0005_action_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_number',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.IntegerField(choices=[(1, 'Number'), (2, 'Select/Multiple Choice')]),
        ),
    ]
